name: Lint with Black

on:
  push:
    paths:
      - src/**
      - tests/**
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: psf/black
        rev: 24.2.0 
        with:
          options: "--check --verbose --exclude docs"
